index:
    pattern:  /
    defaults: { _controller: AcmeIndexBundle:Index:index }
    
test:
    path:      /test/
    defaults:  { _controller: AcmeIndexBundle:Index:test }
    
hello:
    pattern:  /hello/{first_name}/{last_name}
    defaults: { _controller: AcmeHelloBundle:Hello:index, color: green }